### PR TITLE
Use None instead of NoneType for API type annotations

### LINKED ISSUE #1532: [Feature] Pyright strict mode compatibility
Hi! I'm trying to use playwright with my codebase, which uses pyright in strict mode. I'm finding that assertions in the sync API make pyright unhappy, because `NoneType` turns into Unknown:

```python
# pyright: strict

from playwright.sync_api import Page, expect


def test_app(page: Page):
    page.goto("http://127.0.0.1:8000/")
    plot = page.locator("#plot")
    expect(plot).to_have_class("text-center")
```

```sh
$ pyright
No configuration file found.
No pyproject.toml file found.
stubPath /Users/jcheng/Development/jcheng5/nonetype-test/typings is not a valid directory.
Assuming Python platform Darwin
Searching for source files
Found 1 source file
pyright 1.1.268
/Users/jcheng/Development/jcheng5/nonetype-test/test_playwright.py
  /Users/jcheng/Development/jcheng5/nonetype-test/test_playwright.py:9:5 - error: Type of "to_have_class" is partially unknown
    Type of "to_have_class" is "(expected: List[Pattern[str] | str] | Pattern[str] | str, *, timeout: float | None = None) -> Unknown" (reportUnknownMemberType)
1 error, 0 warnings, 0 informations
Completed in 0.634sec
```

If I replace all the `NoneType` annotations in `playwright/sync_api/_generated.py` with `None`, the error goes away.

(I just want to add, this is the only problem I've run into with playwright so far--in every other respect it's been a pleasure to use!)

### PR DESCRIPTION
**Pull request by jcheng5**
Fix #1532

### CODE REVIEW

**Comment by mxschmitt** [comment]
Looks good! Seems the CLA bot did not work, could you try sign the CLA [here](https://cla.opensource.microsoft.com/microsoft/playwright-python?pullRequest=1536)?

**Comment by mxschmitt** [comment]
@jcheng5 would it be possible to sign the CLA [here](https://cla.opensource.microsoft.com/microsoft/playwright-python?pullRequest=1536)?

**Comment by rwoll** [comment]
@jcheng5 Can you sign the CLA or let us know if you already have? Looks like the bot is reporting it as not signed. We will be releasing 1.26 soon, so would love to include this!

Thanks!

**Comment by jcheng5** [comment]
So sorry, this is awkward, but I sent the CLA off to legal 11 days ago or whatever... and used the wrong email address 🤦‍♂️  I hopefully will be able to get their signoff in the next day or two.

**Comment by rwoll** [comment]
Sweet! Just drop a comment here once you get it back, and I will follow up with the land. Cheers!

**Comment by jcheng5** [comment]
OK sorry for the delay--I just signed the CLA. Thank you!

**Pull request merged**
