### PR TITLE
chore: remove redundant code

### PR DESCRIPTION
**Pull request by kumaraditya303**

### CODE REVIEW

**Comment by pavelfeldman** [comment]
Did you re-generate api after changing generators?

**Comment by kumaraditya303** [comment]
There isn't any changes to the generator only removed a redundant line, I have regenerated and there wasn't any changes

**Comment by kumaraditya303** [comment]
Moreover we have ci testing the generator and they are also passing

**Comment by mxschmitt** [comment]
Please do not bump dev dependencies inside such a PR, leave PRs only related to the PR title and don't mix multiple unrelated changes in it.

**Comment by kumaraditya303** [comment]
> Please do not bump dev dependencies inside such a PR, leave PRs only related to the PR title and don't mix multiple unrelated changes in it.

I didn't wanted to do that but the version for black should be bumped for https://github.com/microsoft/playwright-python/pull/748 hence I did that

**Comment by kumaraditya303** [comment]
@mxschmitt Separated it to https://github.com/microsoft/playwright-python/pull/764 and lets get that merged first

**Review by pavelfeldman — APPROVED** [review]

**Pull request merged**
