### PR TITLE
chore: better type annotation for channels

### PR DESCRIPTION
**Pull request by kumaraditya303**
Untitled

### CODE REVIEW

**Comment by kumaraditya303** [comment]
There are linting issues , not sure what it is

**Comment by pavelfeldman** [comment]
You are overwriting recent driver docs with older driver docs. You should run setup.

**Comment by kumaraditya303** [comment]
Done!

**Comment by pavelfeldman** [comment]
Well, you are rewriting entire _generated.py files, there should be only channel-related changes there.

**Review by pavelfeldman — APPROVED** [review]

**Comment by kumaraditya303** [comment]
Thanks @aslushnikov

**Pull request merged**
