### PR TITLE
Fixing a pyee DeprecationWarning

### PR DESCRIPTION
**Pull request by shadowwolf899**
pyee.AsyncIOEventEmitter was moved to pyee.asyncio.AsyncIOEventEmitter, so this PR just fixes two imports

### CODE REVIEW

**Comment by mxschmitt** [comment]
I think we should also bump pyee to `>=9.0.0` inside `setup.py` and `meta.yaml` otherwise it would break.

**Comment by shadowwolf899** [comment]
Went ahead and updated those files

**Comment by mxschmitt** [comment]
It seems like version 9.0 is not available on conda-forge yet: https://github.com/conda-forge/pyee-feedstock/ So we need to look into this one as well. I can try to dig into it tomorrow.

**Comment by mxschmitt** [comment]
I opened https://github.com/conda-forge/pyee-feedstock/pull/15 to fix the pyee conda-forge package. Since this is only about a deprecation warning, we can wait for that a few days.

**Comment by shadowwolf899** [comment]
Thanks! And, definitely no urgency needed. Just wanted to try and get this warning fixed since it comes up every time I run my test scripts

**Pull request closed without merging**
