### PR TITLE
support overloads and add overloads to `wait_for_selector` for when it returns `None`

### PR DESCRIPTION
**Pull request by DetachHead**
- optional arguments are now only automatically converted to keyword arguments if the method has no overloads, because otherwise it can invalidate overloads. it's expected that you explicitly specify what arguments should be keywords, like in the example below

- overloads must be defined using `@api_overload` in order for the generate scripts to be able to see them at runtime.
  ```py
  from playwright._impl._overload import api_overload
  
  @api_overload
  async def wait_for_selector(
      self,
      selector: str,
      *,
      timeout: float = None,
      state: Literal["attached", "visible"] = None,
      strict: bool = None,
  ) -> ElementHandle:
      pass

  @api_overload  # type: ignore[no-redef]
  async def wait_for_selector(
      self,
      selector: str,
      *,
      timeout: float = None,
      state: Literal["detached", "hidden"],
      strict: bool = None,
  ) -> None:
      pass

  async def wait_for_selector(  # type: ignore[no-redef]
      self,
      selector: str,
      *,
      timeout: float = None,
      state: Literal["attached", "detached", "hidden", "visible"] = None,
      strict: bool = None,
  ) -> Optional[ElementHandle]:
      ...
  ```

### CODE REVIEW

**Comment by mxschmitt** [comment]
Hi! Thank you for your contribution! This needs to be added to the generated sync and async APIs, since we expose them and not the implementation classes. See e.g. in `scripts/generate_async_api.py`.

**Comment by DetachHead** [comment]
@mxschmitt i added support for overloads

**Comment by mxschmitt** [comment]
Hey @DetachHead, sorry for the delay. Will talk later with the team about it. We will likely end up adding two more methods to not have to rely on overloads. This gives us the same behaviour across all our languages (.NET, Java, etc.).

- new: `{Page,ElementHandle,Locator,Frame}.wait_for_selector_hidden(state=Literal["detached", "hidden"]...))`
- new: `{Page,ElementHandle,Locator,Frame}.wait_for_selector_visible(state=Literal["visible", "attached"]...))`

**Comment by kumaraditya303** [comment]
Relates https://github.com/microsoft/playwright-python/issues/786

**Comment by mxschmitt** [comment]
Closing since its stale, waiting also for user reports.

**Comment by DetachHead** [comment]
Why close it?

> Will talk later with the team about it. We will likely end up adding two more methods to not have to rely on overloads (since we're adding in the future languages which don't support overloads). This gives us the same behaviour across all our languages (.NET, Java, etc.).

did anything ever come of this?

**Comment by DetachHead** [comment]
@mxschmitt `typing.get_overloads` is being introduced in python 3.11 https://docs.python.org/3.11/library/typing.html#typing.get_overloads

I can look at redoing this mr using it

**Comment by KotlinIsland** [comment]
@mxschmitt  I think this is a good idea, can we see an update on this at all?

**Comment by KotlinIsland** [comment]
Looks like some hard coded overloads were supported in #897

**Pull request closed without merging**
