### PR TITLE
chore: Update dependencies and configure Dependabot for monthly updates

### PR DESCRIPTION
**Pull request by kumaraditya303**
Update dependencies and configure dependabot for monthly updates.

### CODE REVIEW

**Comment by kumaraditya303** [comment]
It would be useful to configure dependabot for this project.

**Comment by mxschmitt** [comment]
I wouldn't optimise the images, since the exact images get used in all the different language providers. For dependencies I think its preferred to update them manually every few months, since its only dev dependencies and does not harm anyone. Would also result in less noise in GitHub notifications for the maintainers.

**Comment by kumaraditya303** [comment]
> I wouldn't optimise the images, since the exact images get used in all the different language providers. For dependencies I think its preferred to update them manually every few months, since its only dev dependencies and does not harm anyone. Would also result in less noise in GitHub notifications for the maintainers.

@mxschmitt optimize images means that the images are compressed their dimensions are untouched

**Comment by mxschmitt** [comment]
> > I wouldn't optimise the images, since the exact images get used in all the different language providers. For dependencies I think its preferred to update them manually every few months, since its only dev dependencies and does not harm anyone. Would also result in less noise in GitHub notifications for the maintainers.
> 
> @mxschmitt optimize images means that the images are compressed and their dimensions are untouched

It wouldn't bring any benefit in terms of performance or speed for new developers since we are using Git and the images are already in the tree like that. So the git clone would also take longer since new unknown binary files got added.

**Comment by kumaraditya303** [comment]
@mxschmitt Dependabot is now configured for monthly

**Comment by pavelfeldman** [comment]
Does this fix any bugs?

**Pull request closed without merging**
