### PR TITLE
add osx-arm64 variant config file

### PR DESCRIPTION
**Pull request by wolfv**
I didn't have a chance to test this yet -- any idea on how to test this easily?

### CODE REVIEW

**Comment by mxschmitt** [comment]
I think no way to test it easily, but we release a new Playwright version shortly, so we can then see if it works!

**Comment by mxschmitt** [comment]
We have build workflows configured, you. could try to add it there as well: https://github.com/microsoft/playwright-python/blob/890af94d3380c6dfbe9fabeaedea6b92aa232b11/.github/workflows/ci.yml#L188-L207

Can you actually publish m1 from a amd mac?

**Comment by wolfv** [comment]
Does the `pip setup.py` download any binaries from the internet? We might have to tell it to grab the appropriate ones for `osx-arm64` as otherwise it migth think that it's still on `osx-64`.

All the `osx-arm64` packages on conda-forge are built by cross-compiling so it should work fine from the "conda-side".

**Comment by wolfv** [comment]
Just FYI cross compiling with conda-build works by putting the dependencies for the build platforms (osx-64) that need to run _during_ build in the `build` section of the recipe, and the ones that are linked against in the `host` section (that section will use packages from the `osx-arm64` architecture.

**Comment by mxschmitt** [comment]
> Does the pip setup.py download any binaries from the internet?

Yes it does.

By default it builds wheels containing the driver for the current platform/architecture. See [here](https://github.com/microsoft/playwright-python/blob/890af94d3380c6dfbe9fabeaedea6b92aa232b11/setup.py#L126-L135). You can pass `--all` and then it builds all the wheels. I think as of today the issue is that it builds only the current platform/arch by default, so we require conda to run on this specific arch to be able to get the corresponding wheel while publishing the conda package. 

> We might have to tell it to grab the appropriate ones for osx-arm64 as otherwise it migth think that it's still on osx-64.

Yes I think thats what we need to do. And then tell conda to invoke setup.py per platform.

**Comment by mxschmitt** [comment]
Closing as per above. If anyone wants to revisit this in the future, feel free to create a new PR, thanks!

**Comment by mxschmitt** [comment]
Actually let me re-open, things have changed, GitHub now has M1 runners, do you mind adding this to the matrix? Then it should work I believe: https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by mxschmitt** [comment]
Landed in https://github.com/microsoft/playwright-python/issues/1745.

**Comment by mxschmitt** [comment]
This should be fixed as part of v1.43.0

**Comment by wolfv** [comment]
Thanks!

**Pull request closed without merging**
