### PR TITLE
feat: conda python 3.10

### PR DESCRIPTION
**Pull request by kumaraditya303**

### CODE REVIEW

**Comment by kumaraditya303** [comment]
cc @mxschmitt merge

**Comment by mxschmitt** [comment]
Without this change its not possible for Python 3.10 conda users to use Playwright? Can't we publish a single package per OS instead of also per Python version?

**Comment by kumaraditya303** [comment]
> Without this change its not possible for Python 3.10 conda users to use Playwright? Can't we publish a single package per OS instead of also per Python version?

Yes, the latter is out of scope of this PR. Feel free to do it.

**Comment by mxschmitt** [comment]
Do you have some doc pointers how this can be accomplished? Thanks in advance.

**Comment by kumaraditya303** [comment]
> Do you have some doc pointers how this can be accomplished? Thanks in advance.

@mxschmitt  This will be useful https://www.anaconda.com/blog/condas-new-noarch-packages, Can you merge this so that playwright can be installed on 3.10 and improve later on ?

**Pull request merged**
