### PR TITLE
fix: fix greenlet version for compatibility with pypy

### PR DESCRIPTION
**Pull request by kumaraditya303**

### CODE REVIEW

**Comment by kumaraditya303** [comment]
@mxschmitt Request to review

**Comment by mxschmitt** [comment]
Any resource available for that? Or did a user face into that problem?

**Comment by kumaraditya303** [comment]
I myself was trying to use it with pypy, the problem is that pypy comes pre-installed with a greenlet version which was earlier incompatible , with this PR it is fixed.
You can try it in docker container
```console
$ docker run --rm -it pypy:3 bash
```
@mxschmitt

**Comment by jamadden** [comment]
Since greenlet is built-in to PyPy, the better way to fix this is to specify that the greenlet dependency is CPython specific using [PEP 496 environment markers](https://www.python.org/dev/peps/pep-0496/), e.g., gevent writes its dependency as:
```python
'greenlet >= 0.4.17, < 2.0; platform_python_implementation=="CPython"'
```

**Pull request merged**
