### PR TITLE
fix: patch bug in locals_to_params

### PR DESCRIPTION
**Pull request by danphenderson**
Calls to `locals_to_params` now handle nested params properly.

See [comment](https://github.com/microsoft/playwright-python/issues/1269#issuecomment-1945102293) in issue: 1269

### CODE REVIEW

**Review by A1exKH — APPROVED** [review]
Code LGTM.

**Review by A1exKH — CHANGES_REQUESTED** [review]
@danphenderson please sync your branch with base branch.

**Comment by mxschmitt** [comment]
Looks like generally speaking we can do something like that but we need to skip the logic for `json_data` like we do in .NET: https://github.com/search?q=repo%3Amicrosoft%2Fplaywright-dotnet+DefaultJsonSerializerOptionsKeepNulls&type=code

**Comment by mxschmitt** [comment]
Somewhere https://github.com/microsoft/playwright-python/blob/04b78516a96fb18d0df912652698d0d5b6a55bb6/tests/async/test_browsercontext_proxy.py and https://github.com/microsoft/playwright-python/blob/04b78516a96fb18d0df912652698d0d5b6a55bb6/tests/async/test_proxy.py#L49

**Comment by danphenderson** [comment]
Thanks, the test coverage has been added - please let me know if any additional changes are needed.

**Review by mxschmitt — APPROVED** [review]

**Pull request merged**
