### PR TITLE
(🎁) Add `|` operator on `Locator`s

### PR DESCRIPTION
**Pull request by KotlinIsland**
umm, based python moment????

### CODE REVIEW

**Comment by KotlinIsland** [comment]
@microsoft-github-policy-service agree

**Comment by mxschmitt** [comment]
I guess the same makes sense for and? Will discuss with the team later!

**Comment by KotlinIsland** [comment]
@mxschmitt Do you mean and as in an operator for `filter`?

**Comment by mxschmitt** [comment]
(Never mind, `Locator.and(...)` was something we were experimenting with and I got confused, we didn't ship it)

**Review by mxschmitt — APPROVED** [review]

**Comment by mxschmitt** [comment]
We decided for now to keep _or instead of | since or_ also provides auto completion support and shows what it is actually doing. Thanks for you suggestion tho!

**Comment by KotlinIsland** [comment]
# Workaround

```py
from playwright.sync_api import Locator

Locator.__or__ = Locator.or_
```

**Comment by DetachHead** [comment]
@mxschmitt it seems silly to not accept this PR when the alternative is to append an underscore to the method name as a workaround for the fact that "or" causes a syntax error.

```py
page.locator('div') | page.locator('span')
```
looks much less gross than
```py
page.locator('div').or_(page.locator('span'))
```

python specifically supports this use case, why not take advantage of it?

**Pull request closed without merging**
