### PR TITLE
chore: show code coverage in CI

### PR DESCRIPTION
**Pull request by kumaraditya303**

### CODE REVIEW

**Comment by kumaraditya303** [comment]
@mxschmitt Ready for merge!

**Comment by mxschmitt** [comment]
What value does this give us? Having the % per file is not very useful. I think running it locally should be enough there you can also inspect which lines are not covered.

Feel free to create tests for uncovered lines (I know there are a bunch of them).

**Comment by kumaraditya303** [comment]
This would give a timeline of test coverage, also it consume time in running several tests locally, it also gives us a rough idea where the code coverage is less in which files.
Any reason to not do this ?

**Comment by pavelfeldman** [comment]
Line coverage does not give us anything - we can still miss passing one argument over the channel and while status would be happy, tool would be broken. Would not want this false positive on the dashboard.

**Pull request closed without merging**
