### PR TITLE
Add osx-arm64 and linux-aarch64 conda package builds

### LINKED ISSUE #1745: [BUG] Can't install Playwright with Conda on M1 Mac
**Context:**
- Playwright Version: `v1.30`
- Operating System: `MacOS Ventura 13.1`
- Python version: `3.9`
- Extra: `conda 22.11.1`

**Code Snippet**
```
% conda create -n test_playwright python=3.9

% conda activate test_playwright

% conda install -c microsoft playwright
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions
```

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Adds cross-compile builds for conda packages, so that playwright-python can be installed on Apple Silicon (osx-arm64) and ARM (linux-aarch64).

Fixes #1745

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
This is ready for review @mxschmitt

**Comment by Tobias-Fischer** [comment]
@microsoft-github-policy-service agree company="Queensland University of Technology"

**Comment by mxschmitt** [comment]
Hello, thanks for your contribution! I tried to execute this locally on my linux machine, but getting an error that the argument is not available:

    conda build: error: unrecognized arguments: --target-platform=linux-aarch64

I also did not find [documentation](https://docs.conda.io/projects/conda-build/en/stable/resources/commands/conda-build.html) for this command either. What do I do differently?

**Comment by Tobias-Fischer** [comment]
Hi @mxschmitt - you are completely right, this syntax does not work for `conda build`. I am used to using https://github.com/mamba-org/boa where this is an option. I fixed up the PR - it would be great if you could have another look.

**Comment by manglav** [comment]
ping on this?

**Comment by cdeil** [comment]
@mxschmitt - any chance to merge this in?

Would be super to have conda packages on Mac. :-)

**Comment by Tobias-Fischer** [comment]
Check https://anaconda.org/tobiasrobotics/playwright if you need it

**Review by mxschmitt — APPROVED** [review]

**Pull request merged**
