### PR TITLE
chore: only publish wheels package on Pypi

### LINKED ISSUE #312: Playwright on unsupported platforms
On [PyPI](https://pypi.org/project/playwright/#files) the source distribution of the project is uploaded as a result on unsupported platforms, running `pip install playwright` installs the project without playwright-cli and the user does not has access to [build_package.py](https://github.com/microsoft/playwright-python/blob/master/build_package.py). It is better to upload only the wheel of the supported platforms to PyPI so that the unsupported platforms does not download the source code and cause errors.

### PR DESCRIPTION
**Pull request by mxschmitt**
Fixes #312

The failing CI is not related.

### CODE REVIEW

**Comment by pavelfeldman** [comment]
I don't think this fixes anything, there is still no recipe on how to use Playwright on unsupported platforms.

**Comment by mxschmitt** [comment]
> I don't think this fixes anything, there is still no recipe on how to use Playwright on unsupported platforms, or perhaps, I am missing something?

With this change Pip raises a unsupported platform error. Before that it leads to a broken installation.

**Comment by kumaraditya303** [comment]
> > I don't think this fixes anything, there is still no recipe on how to use Playwright on unsupported platforms, or perhaps, I am missing something?
> 
> With this change Pip raises a unsupported platform error. Before that it leads to a broken installation.

Yes, because of this error it is clear that the user's platform isn't supported not that it is a problem of playwright!

**Comment by pavelfeldman** [comment]
Merged as a part of another PR

**Pull request closed without merging**
