### PR TITLE
docs(readme): use aka.ms Playwright Slack invite link

### PR DESCRIPTION
**Pull request by mxschmitt**
These links expire after a certain time and use-count. Would be cool if we can use this everywhere to manage it easily.

### CODE REVIEW

**Comment by pavelfeldman** [comment]
Which one expired? The one we have upstream as well?

**Comment by mxschmitt** [comment]
> Which one expired? The one we have upstream as well?

Not yet expired but expires probably in the future and then we only have to adjust the aka.ms redirect.

**Review by pavelfeldman — APPROVED** [review]
Could you make me Lusha or me the owner of the link?

**Comment by mxschmitt** [comment]
> Could you make me Lusha or me the owner of the link?

current owner is @arjunattam I think. (It's internal only the shortener.)

**Pull request merged**
