### PR TITLE
Update example to use context manager

### PR DESCRIPTION
**Pull request by ranmocy**
It makes sure resources are released. And less lines of code.

These usages are tested under:

https://github.com/microsoft/playwright-python/blob/59369fe126f49c10597d5c9099840bdc8ccdcf15/tests/sync/test_context_manager.py

https://github.com/microsoft/playwright-python/blob/59369fe126f49c10597d5c9099840bdc8ccdcf15/tests/async/test_context_manager.py

### CODE REVIEW

**Comment by ranmocy** [comment]
@microsoft-github-policy-service agree

**Comment by mxschmitt** [comment]
Thank you for your contribution. We learned over the past few years while context managers are great to use, that the community often miss-understands them, so we prefer keeping it as it is.

**Comment by ranmocy** [comment]
@mxschmitt Thanks for replying. Is there any related thread or docs talking about the common mistakes? I'm very curious to learn about them.

**Comment by mxschmitt** [comment]
e.g. think about that you use a context manager to get a page, you use it after the expect and wonder, why is it closed? We saw this is a popular pattern which confused users.

**Pull request closed without merging**
