### PR TITLE
chore:better type for permissions

### PR DESCRIPTION
**Pull request by kumaraditya303**

### CODE REVIEW

**Comment by kumaraditya303** [comment]
@mxschmitt I have given permission to edit PR by maintainers, can you help to fix the linting issue ?

**Review by mxschmitt — APPROVED** [review]

**Comment by kumaraditya303** [comment]
@mxschmitt I have generated the api but still it is showing linting errors not sure about it

**Comment by kumaraditya303** [comment]
Even after rebasing to master it is failing

**Review by pavelfeldman — COMMENTED** [review]
Since those can be browser-specific, I don't think we should suggest those.

**Comment by kumaraditya303** [comment]
https://playwright.dev/docs/api/class-browsercontext#browsercontextgrantpermissionspermissions-options as per the docs there isn't any browser specific permission

**Pull request closed without merging**
